# What this workflow does:
# 1. Install the Notebook2REST tool, and feed the notebooks to it
# 2. Build a docker image of the resulting API, with a new specific versionnumber/tag-name
# 3. Push the docker image to Amazon ECR
# 4. Log in to AWS, and redeploy the helm chart with the new image tag

name: Testpipeline_Notebook2REST

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.ipynb'
      - '**/*.naavrewf'
      - "n2res/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # NOTE: THIS JOB IS A SAMPLE OF HOW WE CAN DO IT LATER
  notebook2rest-setup:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      EKS_CLUSTER_NAME: notebook2rest_cluster

    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::259361438396:role/HelmchartDeployer
        aws-region: ${{ env.AWS_REGION }}

    - name: Debug AWS identity
      run: aws sts get-caller-identity

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy Helm
      run: helm upgrade --install my-api ./n2res --namespace default --kubeconfig $HOME/.kube/config --set image.repository=259361438396.dkr.ecr.eu-north-1.amazonaws.com/notebook2rest/api --set image.tag=ba845f30dd926ad55cdfa5e35414e7d15f35895f-15